### ISSUE TITLE
[CHAT] chat broken

### ISSUE THREAD

**Issue by SimeonC96** [thien/dinno#99]
`{ from: '8', contents: 'Test' }
{ from: '8',
  contents: 'Test',
  sendername: 'Simeon',
  day: 'Saturday 15th April',
  timestamp: '23:54' }
{ Error: ER_BAD_NULL_ERROR: Column 'ToID' cannot be null
    at Query.Sequence._packetToError (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Connection.query (C:\Users\Simeon\Desktop\dinno\node_modules\mysql\lib\Connection.js:208:25)
    at C:\Users\Simeon\Desktop\dinno\functions\chat.js:112:12
    at Object.saveMessage (C:\Users\Simeon\Desktop\dinno\functions\chat.js:111:12)
    at C:\Users\Simeon\Desktop\dinno\functions\socket.js:36:22
    at process._tickCallback (internal/process/next_tick.js:103:7)
  code: 'ER_BAD_NULL_ERROR',
  errno: 1048,
  sqlState: '23000',
  index: 0 }
(node:5400) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ER_BAD_NULL_ERROR: Column 'ToID' cannot be null`

ToID is not set

EDIT: Invalid character as well "`"

var dayHeader = `<div class='alert alert-info msg-date'> <strong> ${msg.day} </strong></div>`;

**Comment by JJ97** [comment]
Looks like its ie only. will fix when in durham

**Comment by JJ97** [comment]
Works in IE11 👌🏻
